# Generated by Django 5.1.2 on 2024-10-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('cityId', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('employment_start', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('job_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentTerms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agreed_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_start_date', models.DateField()),
                ('salary_end_date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_terms', to='Employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Employees.jobtitle'),
        ),
    ]
