# Generated by Django 5.1.1 on 2024-10-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_department_departmenthistory'),
        ('Employees', '0003_SalaryPayment'),
    ]

    operations = [
    ]
