# Generated by Django 5.1.1 on 2024-10-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0004_merge_20241031_1636'),
        ('Employees', 'WorkingHours'),
    ]

    operations = [
    ]
